### ISSUE TITLE
MVP submission notes

### ISSUE THREAD

**Issue by ItamarShDev** [Bu1ly/Ein-Prat-The-Academy-For-Leadership#18]
- [x] create iteration 2 page
  - [x] define tasks
  - [x] add unfinished tasks
- [x]  code reviews
- [x]  explain test methods
- [x] add iteration conclusion
- [x] add retro perspective

**Comment by OriHalyo** [comment]
@ItamarShDev 
Done!
יש עוד איטרציה מלבד איטרציה 2? או שאיטרציה 3 זה כבר ההצגה?

**Comment by ItamarShDev** [comment]
you need at least 3 iterations
you need to finish your goals
and have at least 2 class reviews
all written [here](http://jce-il.github.io/se-class16b/morea/planning//experience-project6-iterations.html) from day one
