### ISSUE TITLE
project3-srs-submission

### ISSUE THREAD

**Issue by Bu1ly** [Bu1ly/Ein-Prat-The-Academy-For-Leadership#2]
@ItamarShDev 
https://github.com/Bu1ly/Ein-Prat-The-Academy-For-Leadership/wiki/SRS---Software-Requirements-Specification

**Comment by Bu1ly** [comment]
srs submission

**Comment by ItamarShDev** [comment]
use cases table isnt quite it.
you need to change it to actual cases and the members how this relevant for

report here on fixing

**Comment by Bu1ly** [comment]
Hi, can you explain yourself better? didnt quite understand what you mean.

We got 3 entities: senior, freshman and admin.

the proj specs is to make  a database of seniors for the freshmans so they
can  look up for seniors for help and etc.

Doesnt our use case covers it all?

**Comment by ItamarShDev** [comment]
use case usually deals with user scenarios.
e.g "i would like my email to stay hidden" ->conclusion: email encoding

**Comment by Bu1ly** [comment]
Hey, its fixed, hope its what u ment... (i looked at other projects
aswell)...

2016-03-26 15:26 GMT+02:00 itamar sharify notifications@github.com:
